### ISSUE TITLE
ref got $editor: undefined

### ISSUE THREAD

**Issue by Thy3634** [e-chan1007/nuxt-monaco-editor#11]
```vue
<script setup>
const editorRef = ref()
onMounted(() => {
    console.log(editorRef.value)
})
</script>
<template>
<MonacoEditor ref="editorRef" />
</template>
```

got this:

```chrome
Proxy {$editor: undefined, __v_skip: true}
```

**Comment by e-chan1007** [comment]
I released [the new version](https://github.com/e-chan1007/nuxt-monaco-editor/releases/tag/v1.0.3) and this error should be fixed successfully.
Now `editorRef.value.$editor` is a `ref`. The document will also be fixed soon.

**Comment by Thy3634** [comment]
@1.0.4 
Not fixed😕

**Comment by Gruce** [comment]
@Thy3634 
Try to remove `node_modules`. Because it works with me.

**Comment by e-chan1007** [comment]
When `onMounted` is called, the editor hasn't been loaded yet, so `editorRef` is undefined then.
After loading is completed, it should be the instance of the editor.

However, it was difficult to detect whether the editor loaded.
Therefore I added the event `load` in [v1.0.5](https://github.com/e-chan1007/nuxt-monaco-editor/releases/tag/v1.0.5). 
The following code should work in this version:
```vue
<script setup>
const onEditorLoaded = (editor) => {
  // `editor` is available!
}
</script>

<MonacoEditor @load="onEditorLoaded" />
```

**Comment by Thy3634** [comment]
No need to do that, vue mount child component first. and the `monaco.editor.create` is sync function

I still blocked by this error `[Vue Router warn]: No match found for location with path "/_monaco/vs/loader.js"`.

I removed pnpm store, and run `nuxi cleanup`, then reinstall. 

I'll try reinstall node.

**Comment by Thy3634** [comment]
It's a version mismatching mistake. I updated nuxt, OK now.

Thank you for your attention.
