### ISSUE TITLE
Blank load

### ISSUE THREAD

**Issue by VandrerenErik** [e-chan1007/nuxt-monaco-editor#17]
The editor is completely blank, and there are no errors anywhere.

![image](https://user-images.githubusercontent.com/54407345/213369673-5a48b910-091d-49e4-ac4d-9b6982df9d67.png)

**Comment by VandrerenErik** [comment]
The problem seem to be width and height

**Comment by VandrerenErik** [comment]
Some of my custom CSS was creating the issue. I will close the issue now.

**Comment by VandrerenErik** [comment]
Sorry to bother you reopening the issue again. The CSS thing was just a coincidence. After further testing I've realised that this only happens within a component. If I place MonacoEditor in a page it always works, no problem, but if a place it within a component it fails. I can kinda force it to work by forcing re-render of the component using hot-reloading, basically just moving MonacoEditor from an html element to another and hitting save.

By default not working when inside another component:
![image](https://user-images.githubusercontent.com/54407345/213613064-9466841b-6002-4013-8c17-e2369c29a4ef.png)


Works after triggering Hot reloading:
![image](https://user-images.githubusercontent.com/54407345/213612988-3c9d40f8-0e5e-4f38-96bd-d807771678d2.png)

**Comment by e-chan1007** [comment]
Did you set the `width` and `height` for `<MonacoEditor>` itself?

With `monaco-editor`, you have to set them for the container element (and then its size will be calculated correctly).
If you remove `style="height: 100%"` on the [playground](https://microsoft.github.io/monaco-editor/playground.html), it looks almost the same as you say.

---
If this has nothing to do with your problem, could you please show me a minimal reproduction?

**Comment by VandrerenErik** [comment]
Yes, I have, and I've actually tried setting it in many different ways. Also, that wouldn't explain why it only fails in this very specific scenario I explained above, basically being too nested.

**Comment by VandrerenErik** [comment]
For now I'm using this absurd workaround:

![image](https://user-images.githubusercontent.com/54407345/213617082-ef5f7100-e0cd-494d-aa42-2590f071a4b8.png)

![image](https://user-images.githubusercontent.com/54407345/213617136-768ed38a-b523-413c-b024-cb8869f6101f.png)

**Comment by e-chan1007** [comment]
This situation looks very strange to me... Nothing seems to be wrong as far as I can see.
I thought that the editor was loaded when the parent element was too small (or hidden) and I tried to reproduce it. However, I couldn't find such a problem.
Since you set the height independently of the parent(I think `h-24` sets its size to `6rem (96px)` when using Tailwind CSS), it should work regardless of the size of the parent.
I'd like to know more details to investigate this issue.

Also, does `:options="{ automaticLayout: true }"` solve this problem?

**Comment by VandrerenErik** [comment]
Yes, "automaticLayout: true" did indeed solve the problem. What you say make sense and I also confirmed it, the parent element was not yet loaded, that also explains why my absurd workaround worked.

Thanks for your help!
