### ISSUE TITLE
DevTools fails to load source maps

### ISSUE THREAD

**Issue by VandrerenErik** [e-chan1007/nuxt-monaco-editor#19]
I keep having this repeating warning, which is a little annoying:

![image](https://user-images.githubusercontent.com/54407345/214867880-955ea649-cf66-4ea2-8ee7-081b9eba046a.png)

I have temporarily disabled source maps, but I'd like to know why this is happening.

**Comment by e-chan1007** [comment]
I might have to rewrite the source map paths provided by monaco-editor.
I'll try to do that later.

**Comment by e-chan1007** [comment]
Finally fixed in [v1.2.2](https://github.com/e-chan1007/nuxt-monaco-editor/releases/tag/v1.2.2).
I have checked that there is no warning with `nuxt@3.3.2`.

I'm sorry you had to wait so long for this issue to be fixed.
