### ISSUE TITLE
Broken in Nuxt 3.2.2

### ISSUE THREAD

**Issue by stenet** [e-chan1007/nuxt-monaco-editor#23]
Looks like the module broke again with Nuxt 3.2.2. Same as mentioned in #20 

In dev mode it works. This is the result of preview:

<img width="472" alt="image" src="https://user-images.githubusercontent.com/1838511/220413614-bf271ee6-563d-49bd-89f7-1d6c74864532.png">

**Comment by e-chan1007** [comment]
I released [v1.1.4](https://github.com/e-chan1007/nuxt-monaco-editor/releases/tag/v1.1.4) and this should fix it.

**Comment by stenet** [comment]
Thank you! Tested it and everything works as expected :)

**Comment by lukas-vollmer** [comment]
Thanks for the fast fix!
