### ISSUE TITLE
Plugin didn't copy sourcemap file to dist/.output folder

### ISSUE THREAD

**Issue by witjs** [e-chan1007/nuxt-monaco-editor#26]
[nuxt] error caught during app initialization H3Error: Page not found: /min-maps/vs/base/common/worker/simpleWorker.nls.js.map
<img width="356" alt="image" src="https://user-images.githubusercontent.com/1400188/226588353-08bc4324-e8b4-4094-b4e2-98e799510bd4.png">

**Comment by e-chan1007** [comment]
I couldn't fix it by just copying sourcemaps.

From v1.2.0, the loader of monaco-editor will be rewritten based on ESM.
This seems to be able to fix this issue as well.

You can try using v1.2.0-beta.2 which was released a while ago.

---

Duplicate to #19, this issue will be closed.
