### ISSUE TITLE
How to change monaco config

### ISSUE THREAD

**Issue by buksy90** [e-chan1007/nuxt-monaco-editor#34]
Hi,

could you please add more documentation on how to change Monaco config?
I'm mostly interested in how to [disable the minimap](https://microsoft.github.io/monaco-editor/docs.html#interfaces/editor.IEditorMinimapOptions.html#enabled).

Thanks

**Comment by cc-hearts** [comment]
The hope can help you

```vue
<script setup lang="ts">
import { ref, watch } from 'vue'

const editorRef = ref(null)

onMounted(() => {
  editorRef.value!.$editor.updateOptions({
    minimap: { enabled: false },
  })
})
</script>
<template>
  <MonacoEditor
    ref="editorRef"
    theme="vs-dark"
  />
</template>
```
