### ISSUE TITLE
Monaco Editor mounting issue

### ISSUE THREAD

**Issue by XStarlink** [e-chan1007/nuxt-monaco-editor#44]
Hello, thank you for this module!

I'm trying to use the editor but I have a problem, when the page loads the first time, the editor loads badly, it looks like there's an mounting problem in the dom.

But after making any modification in the code, the nuxt HMR reloads the view and now the editor appears.

I've made a reproduction here:
https://stackblitz.com/edit/node-nxxysk?file=nuxt.config.ts,app.vue,components%2FAppTopbar.vue,components%2FAppSidebar.vue

Here's a screenshot of the problem
<img width="1728" alt="Capture d’écran 2023-12-07 à 12 26 04" src="https://github.com/e-chan1007/nuxt-monaco-editor/assets/34127019/033d85f8-d365-4c1a-8a74-c5b938ec6c29">

After any code modification, the editor loads
<img width="1367" alt="Capture d’écran 2023-12-07 à 12 23 28" src="https://github.com/e-chan1007/nuxt-monaco-editor/assets/34127019/2c52f33a-ac12-4c04-a659-cdbae0080d70">

**Comment by e-chan1007** [comment]
Adding `automaticLayout: true` should fix this.

```diff vue
  <MonacoEditor
      ref="monacoEditor"
      v-model="editor"
      lang="typescript"
      :options="{
        theme: 'vs-dark',
+       automaticLayout: true,
        lineNumbers: 'on',
        roundedSelection: true,
        scrollBeyondLastLine: false,
        readOnly: false,
      }"
      :style="{
        height: '100%',
        width: '100%',
      }"
   />
```

**Comment by XStarlink** [comment]
> Adding `automaticLayout: true` should fix this.
> 
> ```diff
>   <MonacoEditor
>       ref="monacoEditor"
>       v-model="editor"
>       lang="typescript"
>       :options="{
>         theme: 'vs-dark',
> +       automaticLayout: true,
>         lineNumbers: 'on',
>         roundedSelection: true,
>         scrollBeyondLastLine: false,
>         readOnly: false,
>       }"
>       :style="{
>         height: '100%',
>         width: '100%',
>       }"
>    />
> ```

Thanks a lot for your answer, it works!

Maybe we can put it somewhere in the documentation, for future users who encounter the same problem?
