### ISSUE TITLE
Nuxt 3.9.0 - Shadow DOM issues?

### ISSUE THREAD

**Issue by L422Y** [e-chan1007/nuxt-monaco-editor#46]
Fresh install of Nuxt 3.9.0 and nuxt-monaco-editor fails when trying to access the shadow root - stepped through and domNode is null..

Cannot read properties of undefined (reading 'parentNode')
```
at getShadowRoot (.../_nuxt/node_modules/monaco-editor/esm/vs/base/browser/dom.js?v=2a224e56:520:20)
at Module.isInShadowDOM (.../_nuxt/node_modules/monaco-editor/esm/vs/base/browser/dom.js?v=2a224e56:516:14)
at StandaloneThemeService.registerEditorContainer (.../_nuxt/node_modules/monaco-editor/esm/vs/editor/standalone/browser/standaloneThemeService.js?v=2a224e56:207:17)
at new StandaloneEditor (.../_nuxt/node_modules/monaco-editor/esm/vs/editor/standalone/browser/standaloneCodeEditor.js?v=2a224e56:174:51)
at InstantiationService._createInstance (.../_nuxt/node_modules/monaco-editor/esm/vs/platform/instantiation/common/instantiationService.js?v=2a224e56:97:24)
at InstantiationService.createInstance (.../_nuxt/node_modules/monaco-editor/esm/vs/platform/instantiation/common/instantiationService.js?v=2a224e56:68:27)
at Object.create (.../_nuxt/node_modules/monaco-editor/esm/vs/editor/standalone/browser/standaloneEditor.js?v=2a224e56:44:33)
at .../_nuxt/node_modules/nuxt-monaco-editor/dist/runtime/MonacoEditor.client.js:48:30
at .../_nuxt/node_modules/.cache/vite/client/deps/vue.js?v=475a85ca:4295:88
at callWithErrorHandling (.../_nuxt/node_modules/.cache/vite/client/deps/vue.js?v=475a85ca:1666:18)
```

### Minimal Reproduction

https://stackblitz.com/edit/github-wsgmqi?file=nuxt.config.ts,package.json,app.vue

**Comment by physics515** [comment]
I'm running into the same issue after upgrading.

**Comment by yjl9903** [comment]
My workaround is to wrap the onMounted body in the setTimeout. Since I do not know why the ref is `undefined` while onMounted.

https://github.com/e-chan1007/nuxt-monaco-editor/blob/9954c708debb5f57d53837caa2ca27c29c56ad1e/src/runtime/MonacoEditor.client.vue#L73-L83

```ts
onMounted(() => {
  setTimeout(() => {
    // original code here
  })
})
```

**Comment by jontybrook** [comment]
Ditto this. The above workaround worked for me too. Can this fix be merged to main?

**Comment by jandobrx** [comment]
Having the same issue is the setTimeout the only solution found sofar?

**Comment by jandobrx** [comment]
Also good to note you need to make the same change to the diff editor if using!!!

**Comment by 7836246** [comment]
有没有更好的解决方案
Is there a better solution?

**Comment by johnkomarnicki** [comment]
Having the same issue. Any additional recommendations?

**Comment by jontybrook** [comment]
I've just hacked together a [fix for this on a fork](https://github.com/jontybrook/nuxt-monaco-editor/tree/patch1). I updated deps from this module and wrapped the onMounted in nextTick. This has fixed the issue for me.

Anyone else wanting to use my patched version can do so by sourcing the module from my fork like this:

```
 "dependencies": {
    "monaco-editor": "^0.45.0",
    "nuxt-monaco-editor": "git+https://github.com/jontybrook/nuxt-monaco-editor.git#patch1",
  },
```

**Comment by L422Y** [comment]
I created my own `CustomMonacoEditor.client.vue` which uses a watch to make sure the element is ready, since there's no actual guarantee that elements are there on mount or with `setTimeout`/`nextTick`

```vue
<template>
    <div class="editor">
        <div v-show="!isLoading" ref="editorElement"/>
    </div>
</template>
<script lang="ts" setup>
import type * as Monaco from "monaco-editor"
import { computed, ref, shallowRef, watch } from "vue"
import { defu } from "defu"

interface Props {
    /**
     * Programming Language (Not a locale for UI);
     * overrides `options.language`
     */
    lang?: string;
    /**
     * Options passed to the second argument of `monaco.editor.create`
     */
    options?: Monaco.editor.IStandaloneEditorConstructionOptions;
    modelValue?: string;
}

interface Emits {
    (event: "update:modelValue", value: string): void

    (event: "load", editor: Monaco.editor.IStandaloneCodeEditor): void
}

const props = withDefaults(defineProps<Props>(), {
    lang: () => "plaintext",
    options: () => ( {} ),
    modelValue: () => ""
})

const emit = defineEmits<Emits>()
const isLoading = ref(true)
const lang = computed(() => props.lang || props.options.language)
const editorRef = shallowRef<Monaco.editor.IStandaloneCodeEditor>()
const editorElement = ref<HTMLDivElement>()
const monaco = useMonaco()!
const defaultOptions: Monaco.editor.IStandaloneEditorConstructionOptions = {
    automaticLayout: true
}

let editor: Monaco.editor.IStandaloneCodeEditor
let model: Monaco.editor.ITextModel

watch(() => props.modelValue, () => {
    if (editor?.getValue() !== props.modelValue) {
        editor?.setValue(props.modelValue)
    }
})

watch(() => props.lang, () => {
    if (model) {
        model.dispose()
    }
    model = monaco.editor.createModel(props.modelValue, lang.value)
    editor?.setModel(model)
})

watch(() => props.options, () => {
    editor?.updateOptions(defu(props.options, defaultOptions))
})

watch(editorElement, (newValue, oldValue) => {
    if (!editorElement.value || oldValue) return
    editor = monaco.editor.create(editorElement.value!, defu(props.options, defaultOptions))
    model = monaco.editor.createModel(props.modelValue, lang.value)
    editorRef.value = editor
    editor.layout()
    editor.setModel(model)
    editor.onDidChangeModelContent(() => {
        emit("update:modelValue", editor.getValue())
    })
    isLoading.value = false
    emit("load", editor)
})

defineExpose({
    /**
     * Monaco editor instance
     */
    $editor: editorRef
})

onBeforeUnmount(() => {
    editor?.dispose()
    model?.dispose()
})
</script>

```

**Comment by Sun-ZhenXing** [comment]
@e-chan1007, please merge it to fix this issus. Thanks!

**Comment by andywillekens** [comment]
Don't know if this is the same issue, but since upgrading i'm getting TypeError: domNode is undefined

**Comment by andywillekens** [comment]
> I created my own `CustomMonacoEditor.client.vue` which uses a watch to make sure the element is ready, since there's no actual guarantee that elements are there on mount or with `setTimeout`/`nextTick`
> 
> ```
> <template>
>     <div v-show="!isLoading" ref="editorElement" class="editor"/>
> </template>
> <script lang="ts" setup>
> import type * as Monaco from "monaco-editor"
> import { computed, ref, shallowRef, watch } from "vue"
> import { defu } from "defu"
> 
> interface Props {
>     /**
>      * Programming Language (Not a locale for UI);
>      * overrides `options.language`
>      */
>     lang?: string;
>     /**
>      * Options passed to the second argument of `monaco.editor.create`
>      */
>     options?: Monaco.editor.IStandaloneEditorConstructionOptions;
>     modelValue?: string;
> }
> 
> interface Emits {
>     (event: "update:modelValue", value: string): void
> 
>     (event: "load", editor: Monaco.editor.IStandaloneCodeEditor): void
> }
> 
> const props = withDefaults(defineProps<Props>(), {
>     lang: () => "plaintext",
>     options: () => ( {} ),
>     modelValue: () => ""
> })
> 
> const emit = defineEmits<Emits>()
> const isLoading = ref(true)
> const lang = computed(() => props.lang || props.options.language)
> const editorRef = shallowRef<Monaco.editor.IStandaloneCodeEditor>()
> const editorElement = ref<HTMLDivElement>()
> const monaco = useMonaco()!
> const defaultOptions: Monaco.editor.IStandaloneEditorConstructionOptions = {
>     automaticLayout: true
> }
> 
> let editor: Monaco.editor.IStandaloneCodeEditor
> let model: Monaco.editor.ITextModel
> 
> watch(() => props.modelValue, () => {
>     if (editor?.getValue() !== props.modelValue) {
>         editor?.setValue(props.modelValue)
>     }
> })
> 
> watch(() => props.lang, () => {
>     if (model) {
>         model.dispose()
>     }
>     model = monaco.editor.createModel(props.modelValue, lang.value)
>     editor?.setModel(model)
> })
> 
> watch(() => props.options, () => {
>     editor?.updateOptions(defu(props.options, defaultOptions))
> })
> 
> watch(editorElement, (newValue, oldValue) => {
>     if (!editorElement.value || oldValue) return
>     editor = monaco.editor.create(editorElement.value!, defu(props.options, defaultOptions))
>     model = monaco.editor.createModel(props.modelValue, lang.value)
>     editorRef.value = editor
>     editor.layout()
>     editor.setModel(model)
>     editor.onDidChangeModelContent(() => {
>         emit("update:modelValue", editor.getValue())
>     })
>     isLoading.value = false
>     emit("load", editor)
> })
> 
> defineExpose({
>     /**
>      * Monaco editor instance
>      */
>     $editor: editorRef
> })
> 
> onBeforeUnmount(() => {
>     editor?.dispose()
>     model?.dispose()
> })
> </script>
> ```

I used this code but needed to add onBeforeUnmount to the import and import { useMonaco } from './composables' because those where missing..
