### ISSUE TITLE
Support for themes

### ISSUE THREAD

**Issue by rohitasare7** [e-chan1007/nuxt-monaco-editor#49]
Hi, I would like to know how can I use themes from --> https://github.com/brijeshb42/monaco-themes
I tried the code but couldnt make it work,
Appreciate the help (Sorry for the trouble as I am learning Nuxt, ts)

**Comment by e-chan1007** [comment]
You can use themes with `useMonaco`, `monaco.editor.defineTheme` and `monaco.editor.setTheme`.

Example: https://stackblitz.com/edit/nuxt-starter-dkmgcg?file=app.vue

**Comment by rohitasare7** [comment]
okay thanks alot let me try this!

**Comment by rohitasare7** [comment]
its working fine, appreciate the help!
