### ISSUE TITLE
Can't paste code from clipboard

### ISSUE THREAD

**Issue by Bystrova** [e-chan1007/nuxt-monaco-editor#50]
I can't paste the clipboard data to the editor neither by pressing Ctrl + V, nor by using Paste in context menu in Chrome browser (v 123.0.6312.106)
But in Firefox in works.
In documentation is also works in all browsers https://microsoft.github.io/monaco-editor/

**Comment by rohitasare7** [comment]
I am facing the same issue, CTRL + V not working 😐

**Comment by e-chan1007** [comment]
It might be caused by `monaco-editor@^0.46.0`, but I added workaround to `nuxt-monaco-editor@1.2.9`.
