### ISSUE TITLE
Failed to load source map

### ISSUE THREAD

**Issue by younglet** [e-chan1007/nuxt-monaco-editor#63]
WARN  Failed to load source map for /Users/yanglei/Desktop/x/node_modules/.pnpm/monaco-editor@0.52.0/node_modules/monaco-editor/esm/vs/base/common/marked/marked.js.
Error: An error occurred while trying to read the map file at marked.umd.js.map
Error: ENOENT: no such file or directory, open '/Users/yanglei/Desktop/x/node_modules/.pnpm/monaco-editor@0.52.0/node_modules/monaco-editor/esm/vs/base/common/marked/marked.umd.js.map'

I am just a newbie , can somebody help me  = =

**Comment by masaringr** [comment]
same here. did you find a solution?

**Comment by e-chan1007** [comment]
This issueseems to be related to https://github.com/microsoft/monaco-editor/issues/4712.
I changed some code of `nuxt-monaco-editor` in `v1.3.0` and that warning did not appear in my environment.
Try to use `v1.3.1` and if you still get the warning, set the `removeSourceMaps` option in `nuxt.config.ts` to `true`, which was also added in `v1.3.1`.

**Comment by wcywin** [comment]
I can confirm that the new version of nuxt-monaco-edtitor 1.3.1 has the warning removed :) Thank you @e-chan1007 !

I believe we could set this issue to closed.
