### ISSUE TITLE
How to set model URI in editor?

### ISSUE THREAD

**Issue by parthdedaniya** [e-chan1007/nuxt-monaco-editor#64]
I'm using Monaco-editor in the template tag like below:

`<MonacoEditor v-model="entities" ref="entityEditor" lang="json" :options="editorOptions" />`

Also, I've made a plugin called `monaco-editor.ts` which includes all Monaco-related configuration code.
In this file, I've defined schema for JSON, which is defined like below:

```
monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
        validate: true,
	schemas: [
		{
			uri: "http://my-schema.json",
			fileMatch: ["in-memory://with-schema.json"],
			schema: {
                                //My schema...
                        }
                }
       ]
})
```

Here I've defined fileMatch with my custom string instead of `["*"]` so that it can only be used when I want.

Please help me define the model-URI option in my .vue file. Can it be directly defined in the <MonacoEditor> tag or not?

**Comment by e-chan1007** [comment]
I have added the `modelUri` option to `<MonacoEditor>` in `v1.3.1`.
Try to use it and if you encounter any problems, please ask me again.
